# Generated by Django 2.2.1 on 2019-05-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_universidade', '0002_auto_20190518_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidade',
            name='sigla',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='universidade',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='projeto_universidade.Curso'),
        ),
    ]
