# Generated by Django 2.2.1 on 2019-05-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_universidade', '0003_auto_20190518_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universidade',
            name='img',
        ),
    ]
